# Configuration file for Multi_BLAST pipeline
# -----------------------------------------
# Input directories (specify paths to data files):

assemblies_dir: "/home/nponcelet/Documents/03-Script/00_Projet_Perso/02_Bioinfo/42_Multi_BLAST/Test_data/Assemblies"
queries_dir: "/home/nponcelet/Documents/03-Script/00_Projet_Perso/02_Bioinfo/42_Multi_BLAST/Test_data/Queries"

# Output directory (specify where results will be saved):

analysis_dir: "/home/nponcelet/Documents/03-Script/00_Projet_Perso/02_Bioinfo/42_Multi_BLAST/Test_data/Output"

# BLAST settings
# -----------------------------------------

blast_type: "tblastx"  #  "blastn" or "tblastx"

#header_report: "qseqid sseqid  pident length mismatch gapopen qstart qend sstart send evalue bitscore qseq sseq"

header_report: "qseqid sseqid  pident length qframe sframe sstrand mismatch gapopen qstart qend sstart send evalue bitscore qseq sseq"

# Possible header fields:
# -----------------------------------------
# qseqid     : Query Seq-id
# qgi        : Query GI
# qacc       : Query accession
# qaccver    : Query accession.version
# qlen       : Query sequence length
# sseqid     : Subject Seq-id
# sallseqid  : All subject Seq-id(s), separated by a ';'
# sgi        : Subject GI
# sallgi     : All subject GIs
# sacc       : Subject accession
# saccver    : Subject accession.version
# sallacc    : All subject accessions
# slen       : Subject sequence length
# qstart     : Start of alignment in query
# qend       : End of alignment in query
# sstart     : Start of alignment in subject
# send       : End of alignment in subject
# qseq       : Aligned part of query sequence
# sseq       : Aligned part of subject sequence
# evalue     : Expect value
# bitscore   : Bit score
# score      : Raw score
# length     : Alignment length
# pident     : Percentage of identical matches
# nident     : Number of identical matches
# mismatch   : Number of mismatches
# positive   : Number of positive-scoring matches
# gapopen    : Number of gap openings
# gaps       : Total number of gaps
# ppos       : Percentage of positive-scoring matches
# frames     : Query and subject frames separated by a '/'
# qframe     : Query frame
# sframe     : Subject frame
# btop       : Blast traceback operations (BTOP)
# staxid     : Subject Taxonomy ID
# ssciname   : Subject Scientific Name
# scomname   : Subject Common Name
# sblastname : Subject Blast Name
# sskingdom  : Subject Super Kingdom
# staxids    : Unique Subject Taxonomy ID(s), separated by a ';' (in numerical order)
# sscinames  : Unique Subject Scientific Name(s), separated by a ';'
# scomnames  : Unique Subject Common Name(s), separated by a ';'
# sblastnames: Unique Subject Blast Name(s), separated by a ';' (in alphabetical order)
# sskingdoms : Unique Subject Super Kingdom(s), separated by a ';' (in alphabetical order)
# stitle     : Subject Title
# salltitles : All Subject Title(s), separated by a '<>'
# sstrand    : Subject Strand
# qcovs      : Query Coverage Per Subject
# qcovhsp    : Query Coverage Per HSP
# qcovus     : Query Coverage Per Unique Subject (blastn only)